{
 "title": "K8s-Operator-Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "k8s_cluster",
    "label": "K8s Cluster",
    "query": {
     "query": "label_values(kube_namespace_created,k8s_cluster_id)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_created{k8s_cluster_id=\"${k8s_cluster}\"}, namespace)"
    }
   },
   {
    "name": "operator",
    "label": "Operator",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"${namespace}\", k8s_cluster_id=\"${k8s_cluster}\",pod=~\".*operator.*\"}, pod)"
    }
   },
   {
    "name": "controller",
    "query": {
     "query": "label_values(controller_runtime_active_workers{namespace=\"${namespace}\", k8s_cluster_id=\"${k8s_cluster}\",pod=~\"${operator}\"},  controller)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Reconcile Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average Reconciles/Sec",
   "type": "timeseries",
   "description": "Indicates the total number of reconciliations that occurred within the time frame, categorized by their status.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (controller, result) (rate(controller_runtime_reconcile_total{k8s_cluster_id=~\"${k8s_cluster}\",namespace=~\"${namespace}\",pod=~\"${operator}\",controller=~\"${controller}\"}[$__rate_interval]))",
     "legendFormat": "{{controller}} {{result}}"
    }
   ]
  },
  {
   "title": "Average Reconcile Time(Sec)",
   "type": "timeseries",
   "description": "Average time taken for reconciliation",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum by (controller) (rate(controller_runtime_reconcile_time_seconds_sum{k8s_cluster_id=~\"${k8s_cluster}\",namespace=~\"${namespace}\",pod=~\"${operator}\",controller=~\"${controller}\"}[$__rate_interval])) ",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Active Reconciles count",
   "type": "timeseries",
   "description": "Active reconciliation happening and Max number of reconciliations posssible",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "controller_runtime_active_workers{k8s_cluster_id=~\"${k8s_cluster}\",namespace=~\"${namespace}\",pod=~\"${operator}\",controller=~\"${controller}\"}",
     "legendFormat": "{{controller}}"
    },
    {
     "expr": "controller_runtime_max_concurrent_reconciles{k8s_cluster_id=~\"${k8s_cluster}\",namespace=~\"${namespace}\",pod=~\"${operator}\",controller=~\"${controller}\"}",
     "legendFormat": "Max {{controller}}"
    }
   ]
  },
  {
   "title": "Histogram of Reconcile Time ${controller}",
   "type": "heatmap",
   "description": "Histogram data with buckets of reconcile time ${controller}",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "repeat": "controller",
   "targets": [
    {
     "expr": "sum by (le) ((controller_runtime_reconcile_time_seconds_bucket{k8s_cluster_id=~\"${k8s_cluster}\",namespace=~\"${namespace}\",pod=~\"${operator}\",controller=~\"${controller}\"}[$__rate_interval]))",
     "legendFormat": "{{controller}} {{le}}"
    }
   ]
  },
  {
   "title": "Queue Waiting Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Reconcile Added to Queue/Sec",
     "type": "timeseries",
     "description": "Reconciles added to the Queue per sec",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "/sec" } },
     "targets": [
      {
       "expr": "sum by (controller) (rate(workqueue_adds_total{k8s_cluster_id=~\"${k8s_cluster}\",namespace=~\"${namespace}\",pod=~\"${operator}\",controller=~\"${controller}\"}[$__rate_interval]))",
       "legendFormat": "{{controller}} {{result}}"
      }
     ]
    },
    {
     "title": "Reconciles waiting in Queue",
     "type": "timeseries",
     "description": "Number of Reconcile waiting to be Processed",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "workqueue_depth{k8s_cluster_id=~\"${k8s_cluster}\",namespace=~\"${namespace}\",pod=~\"${operator}\",controller=~\"${controller}\"}",
       "legendFormat": "{{controller}} {{result}}"
      }
     ]
    },
    {
     "title": "Cumulative Unfinished Reconcile Time(Sec)",
     "type": "timeseries",
     "description": "Total time passed to process reconciles which are not finished",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "workqueue_unfinished_work_seconds{k8s_cluster_id=~\"${k8s_cluster}\",namespace=~\"${namespace}\",pod=~\"${operator}\",controller=~\"${controller}\"}",
       "legendFormat": "{{controller}}"
      },
      {
       "expr": "workqueue_longest_running_processor_seconds{k8s_cluster_id=~\"${k8s_cluster}\",namespace=~\"${namespace}\",pod=~\"${operator}\",controller=~\"${controller}\"}[$__rate_interval]",
       "legendFormat": "Longest-Running {{controller}}"
      }
     ]
    },
    {
     "title": "Histogram of Queue Waiting Time ${controller}",
     "type": "heatmap",
     "description": "Histogram data with buckets of reconciles waiting in Queue to be processed for ${controller}",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
     "repeat": "controller",
     "targets": [
      {
       "expr": "sum by (le) ((workqueue_queue_duration_seconds_bucket{k8s_cluster_id=~\"${k8s_cluster}\",namespace=~\"${namespace}\",pod=~\"${operator}\",controller=~\"${controller}\"}[$__rate_interval]))",
       "legendFormat": "{{controller}} {{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Go Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Go Garbage Collection",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(go_gc_duration_seconds_count{k8s_cluster_id=~\"${k8s_cluster}\",namespace=~\"${namespace}\",pod=~\"${operator}\"})",
       "legendFormat": "Instances"
      },
      {
       "expr": "rate(go_gc_duration_seconds_sum{k8s_cluster_id=~\"${k8s_cluster}\",namespace=~\"${namespace}\",pod=~\"${operator}\"}[$__rate_interval])",
       "legendFormat": "Duration"
      }
     ]
    },
    {
     "title": "Number of Go Routines",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "go_goroutines{namespace=~\"${namespace}\", k8s_cluster_id=~\"${k8s_cluster}\",pod=~\"${operator}\"}",
       "legendFormat": "Routines"
      },
      {
       "expr": "go_threads{namespace=~\"${namespace}\", k8s_cluster_id=~\"${k8s_cluster}\",pod=~\"${operator}\"}",
       "legendFormat": "Threads"
      }
     ]
    },
    {
     "title": "Heap Memory",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{namespace=~\"${namespace}\", k8s_cluster_id=~\"${k8s_cluster}\",pod=~\"${operator}\"}",
       "legendFormat": "Objects"
      },
      {
       "expr": "go_memstats_heap_idle_bytes{namespace=~\"${namespace}\", k8s_cluster_id=~\"${k8s_cluster}\",pod=~\"${operator}\"}",
       "legendFormat": "Idle"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{namespace=~\"${namespace}\", k8s_cluster_id=~\"${k8s_cluster}\",pod=~\"${operator}\"}",
       "legendFormat": "In Use"
      },
      {
       "expr": "go_memstats_heap_released_bytes{namespace=~\"${namespace}\", k8s_cluster_id=~\"${k8s_cluster}\",pod=~\"${operator}\"}",
       "legendFormat": "Released"
      }
     ]
    },
    {
     "title": "Objects in Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "go_memstats_heap_objects{namespace=~\"${namespace}\", k8s_cluster_id=~\"${k8s_cluster}\",pod=~\"${operator}\"}",
       "legendFormat": "Object Count"
      }
     ]
    },
    {
     "title": "Go Memory Stats",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_stack_inuse_bytes{namespace=~\"${namespace}\", k8s_cluster_id=~\"${k8s_cluster}\",pod=~\"${operator}\"}",
       "legendFormat": "Stack"
      },
      {
       "expr": "go_memstats_sys_bytes{namespace=~\"${namespace}\", k8s_cluster_id=~\"${k8s_cluster}\",pod=~\"${operator}\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "go_memstats_heap_sys_bytes{namespace=~\"${namespace}\", k8s_cluster_id=~\"${k8s_cluster}\",pod=~\"${operator}\"}",
       "legendFormat": "Heap"
      }
     ]
    },
    {
     "title": "Open File Descriptors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "process_open_fds{namespace=~\"${namespace}\", k8s_cluster_id=~\"${k8s_cluster}\",pod=~\"${operator}\"}",
       "legendFormat": "Object Count"
      }
     ]
    }
   ]
  },
  { "title": "Pod metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Pod CPU Stats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{k8s_cluster_id=\"${k8s_cluster}\",namespace=\"$namespace\", pod=~\"$operator\",container!~\"POD\", image!=\"\",container!=\"\"}[$__rate_interval])) by (k8s_cluster_id,container,pod)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{k8s_cluster_id=\"${k8s_cluster}\",namespace=\"$namespace\", pod=~\"$operator\", unit=\"core\",container!=\"\"}",
     "legendFormat": "LIMIT : {{container}}"
    }
   ]
  },
  {
   "title": "Memory Stats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{k8s_cluster_id=\"${k8s_cluster}\",namespace=\"$namespace\", pod=~\"${operator}\",container!=\"\",container!~\"POD\"}) by (k8s_cluster_id,container,pod)\n",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{k8s_cluster_id=\"${k8s_cluster}\",namespace=\"$namespace\", pod=~\"$operator\", unit=\"byte\"}",
     "legendFormat": "LIMIT: {{container}}"
    }
   ]
  },
  {
   "title": "Network - Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{k8s_cluster_id=\"${k8s_cluster}\",namespace=\"$namespace\", pod=~\"$operator\"}[$__rate_interval])) by (k8s_cluster_id,container,pod)",
     "legendFormat": "{{pod}}(Recieved)"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"$operator\"}[$__rate_interval])) by (k8s_cluster_id,pod,container)",
     "legendFormat": "{{pod}}(Transmitted)"
    }
   ]
  }
 ]
}